fix bug where govtable falls over if table_width = NULL
dfe-analytical-services/shinyGovstyle pull request #111
Opened 2024-12-05 09:28 UTC by jenisayshi

Wrapped the custom table width code to only run if width_overwrite is not null and added tests

2024-12-06 10:07 UTC, sarahmwong requested changes
Thanks Jeni! Fix looks good to me, thank you for adding tests too. Please can we add a line in at the top of the function documentation to clarify that if using width_overwrite, the specified widths for columns need to add up to one? Will just need the R documentation running off again and then happy to merge

2025-01-03 18:01 UTC, cjrace requested changes
Think you've got one small conflict in README, that will need fixing before merging, and I've left one super nitpicky suggestion on spacing in the documentation. If you accept it and commit in GitHub you'll still need to pull and then rerun the documentation to update it. 

Otherwise it all seems to work well, am I right in thinking this PR fixes https://github.com/dfe-analytical-services/shinyGovstyle/issues/78? Gave it a quick test and it seems to 😄 if you reference that in the PR description like 'Fixes #78' then it should automatically link and then close that issue when this PR is merged in

2025-01-03 18:01 UTC, cjrace commented on R/govTable.R
> +#' @param width_overwrite change width.  Need to include width for every column.Columns must add up to 1.
```suggestion
#' @param width_overwrite change width. Need to include width for every column. Columns must add up to 1.
```

2025-01-06 13:48 UTC, sarahmwong approved these changes

2025-01-09 11:54 UTC, cjrace approved these changes

2025-01-23 08:56 UTC, merged