105 update to latest govuk frontend version
dfe-analytical-services/shinyGovstyle pull request #117
Opened 2024-12-06 12:08 UTC by sarahmwong

## Overview of changes

Update to 5.7.1 frontend - adding @cjrace as a reviewer as you've had experience updating this before too!

Everything looks ok apart from value boxes - tested this in master and still looks odd! I've raised #116 for Andy to revisit as this looks like a separate issue.

Removed some old manual changes from the css_changes.md file as no longer relevant

## PR Checklist

- [ ] I have updated the documentation (if needed)
- [ ] I have added or updated tests for these changes (if applicable)
- [ x] I have tested these changes locally using `devtools::check()`

## Reviewer instructions

Run devtools::load_all

Run run_example()

Check that all css changes look ok and functionality still works

2024-12-09 18:07 UTC, cjrace reviewed
Not fully tested everything, but leaving the comments I have for now so they're not lost (as I'm not around tomorrow)

Spotted an issue with accordions (though not cross checked against main yet to see if it's pre-existing)

- Only the 'show' is clickable, if you click on the title of the accordion it doesn't open, though for GDS component it seems like clicking anywhere around the accordion title should also open it? https://design-system.service.gov.uk/components/accordion/

2024-12-09 18:07 UTC, cjrace commented on inst/www/images/govuk-crest.svg
Do we use this anywhere? Looks like the footer crest, though seems odd we didn't already have a version of it? Do we need to point the footer function this this?

2024-12-09 18:07 UTC, cjrace commented on inst/www/css/govuk-frontend-norem.css
Given we just copy this in now (and we are full rem instead of norem), would it make sense to change to leaving the name as the same as the one from the GOV.UK ZIP? I think then it's just a case of updating the attach function to import this sheet as a dependency?

2024-12-11 15:19 UTC, cjrace commented on inst/www/css/govuk-frontend-norem.css
> -    font-size: 16px;
Was removing this font size a GDS or us change? I think a lot of the fonts all seem smaller now than they were? 

Screenshot from this branch (100% zoom in Chrome):
![image](https://github.com/user-attachments/assets/662a8be3-beb6-4a04-9732-47d33daa0e7a)

Screenshot from the master branch (100% zoom in Chrome):
![image](https://github.com/user-attachments/assets/44c0a593-f641-4e24-a653-09776456a304)

2024-12-11 15:24 UTC, cjrace requested changes
Have finished my review now, there's only one other odd thing I've noticed (may or may not be related to the fonts comment)

Select input (dropdown) now cuts the bottom of text off

Before
![image](https://github.com/user-attachments/assets/324e032c-3306-4bed-b0e5-cb26f578c4e4)

After
![image](https://github.com/user-attachments/assets/3a26a3d0-2dbb-4761-8330-31aa2c0bdff6)

2024-12-12 09:04 UTC, sarahmwong commented on inst/www/images/govuk-crest.svg
yes this replaces govuk-crest.png, still sat in the folder here weirdly! I'll double check when I'm back on my personal comp whether this image was removed in the latest zip file or not, and see if we can remove. Footer function points to govuk-footer__copyright-logo in the css which has the right svg file referenced so no need to update I think

2024-12-19 15:27 UTC, sarahmwong commented
Thanks for your comments @cjrace! I think these have been addressed now - think the font fix fixes the selection box (looks like this to me):![image](https://github.com/user-attachments/assets/68bc63c3-0be7-41ca-a688-f5966b310c80)

Accordions issue is pre-existing in master good spot! I've raised #123 for a fix - can ask Jeni to take a look unless you wanted to have a go with faffing with the JS! 😄

2024-12-30 13:59 UTC, cjrace approved these changes
Nice! All looks good, and thanks for updating the css_changes.md to match too

2025-01-02 10:28 UTC, merged